In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

**pip install numpy --upgrade**

**https://numpy.org/**

**Array is a basic data structure in numpy**

When we want to complex calculation we need numpy 

    1) Creation of an arrays
    2) Perform several operations on the arrays 
    3) Integral calculus 
    4) Differential equations 
    5) Statistical operations
    
    
**What is an array**

    1) An indexed collection of homogenous data elements 
    2) It is most commonly used in the programming languages like C,C++ or Java 
    3) By default we dont have array in Python, we have other data structures like Lists, Tuples etc 

In [3]:
ages = [45,65,34,22,35,33]

In [4]:
type(ages)

list

In [5]:
array1 = np.array(ages)

In [7]:
type(array1)

numpy.ndarray

In [10]:
array1[1:5]

array([65, 34, 22, 35])

In [33]:
list1 = [True]

In [16]:
type(list1[3])

float

In [34]:
array2 = np.array(list1)

In [22]:
type(array2[3])

numpy.str_

In [ ]:
1st - String Takes the priority
2nd - Float Takes the priority
3rd - Integer Takes the priority
4th - Boolean Takes the priority

In [35]:
list1

[True]

In [36]:
array2

array([ True])

**Simlarities between Lists and Arrays**

    1) Both can be used to store the data
    2) The order will be preserved in both, indexing and slicing concepts will be the same
    3) Both are mutable in nature, we can change the values in both

In [39]:
array1[4]=22

In [40]:
array1

array([45, 65, 34, 22, 22, 33])

**Differences between Lists and Arrays**

    1) List is by default comes in Python, however, if you want arrays you have to install numpy in your machine
    
    2) List can contain heterogeneous data, however, array can only have homogeneous data
    
    3) On the list we cannot perform vectorised operations
    
    4) Arrays consume less memory 
    
    5) Arrays are faster as compare to list 
    
    6) Arrays are most convinient for doing the most complex calculations

In [42]:
sales = [5655,4545,2345,4544]
profit = [555,343,543,233]

for i in range(len(sales)):
    print(profit[i]/sales[i])

0.09814323607427056
0.07546754675467547
0.23155650319829424
0.051276408450704226


In [43]:
sales_array = np.array(sales)

In [44]:
profit_array = np.array(profit)

In [45]:
profit_array

array([555, 343, 543, 233])

In [46]:
sales_array

array([5655, 4545, 2345, 4544])

In [47]:
profit_array/sales_array

array([0.09814324, 0.07546755, 0.2315565 , 0.05127641])

In [48]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [49]:
sales*3

[5655, 4545, 2345, 4544, 5655, 4545, 2345, 4544, 5655, 4545, 2345, 4544]

In [50]:
sales_array*3

array([16965, 13635,  7035, 13632])

In [51]:
sales_array

array([5655, 4545, 2345, 4544])

In [53]:
sales_array.size

4

In [54]:
sales_array.ndim

1

In [55]:
sales_us = [4565,3454,3232,3454]
sales_eu = [7666,4566,6455,3434]
sales_in = [6534,6566,4455,6755]

In [57]:
sales_matrix = np.array([sales_us,sales_eu,sales_in])

In [56]:
[sales_us,sales_eu,sales_in]

[[4565, 3454, 3232, 3454], [7666, 4566, 6455, 3434], [6534, 6566, 4455, 6755]]

In [58]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [59]:
sales_matrix[2,2]

4455

In [60]:
sales_matrix[1:3,1:3]

array([[4566, 6455],
       [6566, 4455]])

In [61]:
sales_matrix[1:,1:3]

array([[4566, 6455],
       [6566, 4455]])

In [62]:
sales_matrix.size

12

In [63]:
sales_matrix.ndim

2

In [64]:
sales_matrix.shape

(3, 4)

In [65]:
sales_array.shape

(4,)

In [66]:
sales_array

array([5655, 4545, 2345, 4544])

In [68]:
sales_array.T.shape

(4,)

In [71]:
sales_matrix.T.shape

(4, 3)

In [73]:
sales_array.shape

(4,)

In [74]:
sales_array

array([5655, 4545, 2345, 4544])

In [95]:
profit_us = [454,342,353,433]
profit_eu = [544,233,432,655]
profit_in = [344,333,234,545]

In [96]:
profit_matrix = np.array([profit_us,profit_eu,profit_in])

In [97]:
profit_matrix

array([[454, 342, 353, 433],
       [544, 233, 432, 655],
       [344, 333, 234, 545]])

In [98]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [99]:
np.round(profit_matrix/sales_matrix,3)

array([[0.099, 0.099, 0.109, 0.125],
       [0.071, 0.051, 0.067, 0.191],
       [0.053, 0.051, 0.053, 0.081]])

In [82]:
profit_matrix

array([[454, 342, 353, 232],
       [544, 233, 432, 232],
       [344, 333, 234, 233]])

In [83]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [87]:
profit_matrix*sales_matrix

array([[2072510, 1181268, 1140896,  801328],
       [4170304, 1063878, 2788560,  796688],
       [2247696, 2186478, 1042470, 1573915]])

In [104]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [106]:
sales_array.shape

(4,)

In [111]:
a = sales_array.reshape(1,4)

In [112]:
a.shape

(1, 4)

In [113]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [114]:
import pandas as pd

In [117]:
df = pd.DataFrame(sales_matrix,columns=['Q1','Q2','Q3','Q4'])

In [119]:
type(df)

pandas.core.frame.DataFrame

In [120]:
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [122]:
pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [123]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [124]:
def square(num):
    print(num*num)

In [125]:
square(10)

100


In [135]:
class Square:
    def __init__(self,num):
        self.num=num
        
    def sq(self):
        print(self.num*self.num)

In [134]:
num1 = Square(10)
num1.sq()

100


In [130]:
num1

In [131]:
num2 = Square(15)

In [132]:
num2

In [136]:
list1 = [1,2,3,4]

In [138]:
print(type(list1))


<class 'list'>


In [141]:
sales_array.mean()

4272.25

In [142]:
np.mean(sales_array)

4272.25

In [145]:
sales_matrix.mean()

5094.666666666667

In [152]:
np.var(sales_matrix,axis=1)

array([ 271506.1875, 2685158.1875,  884634.25  ])

In [148]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [149]:
np.mean(sales_matrix,axis=0)

array([6255.        , 4862.        , 4714.        , 4547.66666667])

In [154]:
sales_matrix[np.where(sales_matrix>6500)]

array([7666, 6534, 6566, 6755])

In [155]:
sales_matrix

array([[4565, 3454, 3232, 3454],
       [7666, 4566, 6455, 3434],
       [6534, 6566, 4455, 6755]])

In [158]:
np.where(sales_matrix>6500)

(array([1, 2, 2, 2], dtype=int64), array([0, 0, 1, 3], dtype=int64))

In [159]:
sales_matrix[sales_matrix>6500]

array([7666, 6534, 6566, 6755])

In [160]:
sales_matrix>6500

array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])